config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :image,  presence: true
  validates :content, length: { maximum: 100 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  has_secure_password
  validates :password, length: { minimum: 6 }

  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[show edit update destroy]

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        flash[:success] = "写真を投稿しました"
        redirect_to pictures_path
      else
        flash[:danger] = "入力に誤りがあります"
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      flash[:success] = "記事を編集しました"
      redirect_to pictures_path
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    flash[:success] = "記事を削除しました"
    redirect_to pictures_path
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    if @picture.invalid?
      flash[:danger] = "入力に誤りがあります"
      render :new
    end
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i[new create]

  def new
    render layout: false
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "ログインしました"
      redirect_to pictures_path
    else
      flash[:danger] = "ログインできませんでした"
      render :new, layout: false
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
      flash[:success] = "アカウントを作成しました"
    else
      flash[:danger] = "入力に誤りがあります"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "create"
      confirm_pictures_path
    elsif action_name == "edit"
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert-wrapper">
    <div class="alert alert-<%= message_type %>">
      <%= message %>
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert-wrapper">
    <div class="alert alert-<%= message_type %>">
      <%= message %>
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="copyright">DIVIC Corp. © 2023 </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header clearfix">
  <%= link_to pictures_path do %>
    <%= image_tag '/assets/dp_icon.jpg', class: 'icon-image' %>
  <% end %>
  <div class="top_menu clearfix">
    <ul>
      <% if logged_in? %>
        <li><%= link_to 'ホーム', pictures_path %></li>
        <li><%= link_to '投稿する', new_picture_path %></li>
        <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
      <% else %>
        <li><%= link_to "サインアップ", new_user_path %></li>
        <li><%= link_to "ログイン", new_session_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DPbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'normalize', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="wrapper">
      <header class="header clearfix">
        <%= link_to pictures_path do %>
          <%= image_tag '/assets/dp_icon.jpg', class: 'icon-image' %>
        <% end %>
        <div class="top_menu clearfix">
          <ul>
            <% if logged_in? %>
              <li><%= link_to '投稿する', new_picture_path %></li>
              <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
              <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "サインアップ", new_user_path %></li>
              <li><%= link_to "ログイン", new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </header>
      <%= render 'layouts/flash_messages' %>
      <div class="content clearfix">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'normalize', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/flash_message' %>
    <%= render 'layouts/header' %>
    <div class="wrapper">
      <div class="content clearfix">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<% content_for(:title, formtitle) %>
<div class="col-12 col-md-6 px-0 pb-2">
  <%= form_with(model: @picture, local: true, url: choose_new_or_edit ) do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :content %>
    <div class="post-img-preview" id="prv">
      <% if @picture.image && @picture.image.url %>
        <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      <% else %>
        <h5>ここに選択した画像が表示されます</h5>
      <% end %>
    </div>
  </div>
  <div class="col-12 col-md-6 px-0 pl-md-3 pb-2">
    <div class="post-form">
      <div class="input-container post-title">
        <h4>
          <%= formtitle %>
        </h4>
        <% if @picture.errors.any? %>
          <div class="form-error-message">
            <h5>以下のエラーがあります。</h5>
            <div id="error_explanation">
              <ul>
                <% @picture.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
        <div class="form-container">
          <div class="input-container">
            <%= form.file_field :image, class:"form-control post-file-field", placeholder:"画像を選択する" %>
          </div>
          <div class="input-container">
            <%= form.text_area :content, rows: 3, placeholder:"コメントを入力（最大100文字）", class:"form-control form-control-lg" %>
          </div>
          <div class="button-container">
            <%= form.submit btnlabel, class:"btn btn-primary btn-lg w-100" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/pictures/confirm.html copy.erb
<% content_for(:title, '投稿内容の確認') %>
<div class="confirm-area">
  <h4>投稿内容の確認</h4>
  <div>
    <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
      <div class="card-wrapper">
        <div class="card" style="width: 30rem;">

          <%= image_tag @picture.image.url, class: "card-img-top"%>

          <div class="card-body">

            <h4 class="card-title"><%= @picture.content %></h4>

            <div class="card-text">by <%= @picture.user.name %></div>

            <div class="card-button">
              <span class="bi bi-info-square" title="詳細"></span>
              <span class="bi bi-pencil-square" title="編集不可"></span>
              <span class="bi bi-trash" title="削除不可"></span>
            </div>

          </div>

        </div>
      </div>
      <div class="button-container">
        <%= form.submit  "投稿する", class:"btn btn-primary btn-lg w-100" %>
      </div>
    <% end %>
    <%= form_with(model: @picture, url:new_picture_path, local:true, method:"get") do |form| %>
      <%= form.hidden_field :image_cache %>
      <div class="button-container">
        <%= form.submit "編集に戻る", name: 'back', class:"btn btn-secondary btn-lg w-75" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/confirm.html.erb
<% content_for(:title, '投稿内容の確認') %>
<div class="show-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
          <%= form.hidden_field :image_cache %>
          <%= form.hidden_field :content %>
          <div>
            <div class="article-container">
              <div class="article-header">
                <div class="article-data">
                  <strong><span><%= @picture.user.name %></span></strong>
                </div>
              </div>
              <div>
                <div class="article-content">
                  <h4><%= @picture.content %></h4>
                </div>
                <div class="article-img-preview">
                  <%= image_tag @picture.image.url %>
                </div>
              </div>
            </div>
            <div class="button-container">
              <%= form.submit  "投稿する", class:"btn btn-primary btn-lg w-100" %>
            </div>
          </div>
        <% end %>
        <%= form_with(model: @picture, url:new_picture_path, local:true, method:"get") do |form| %>
          <div class="button-container">
            <%= form.hidden_field :image_cache %>
            <%= form.hidden_field :content %>
            <%= form.submit "編集に戻る", name: 'back', class:"btn btn-secondary btn-lg w-50" %>
          </div>
        <% end %>
      </div>
      <div class="back-button">
      </div>
    </div>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="post-wrapper">
  <div class="container-fluid">
    <div class="row justify-content-between">
      <%= render partial: "form", locals: { formtitle: "投稿を編集", btnlabel:"保存する" } %>
    </div>
  </div>
</div>

app/views/pictures/index.html.erb
<% content_for(:title, 'DPbook') %>
<div class="picture-wrapper">
  <div class="picture-display">
    <div class="row">
      <%if @pictures.present? %>
        <% @pictures.each do |picture| %>
          <div class="col-12 col-sm-6 col-md-4 col-lg-3">
            <div class="card" style="width: 14rem;">
              <div class="card-picture">
                <%= link_to picture_path(picture.id) do %>
                  <%= image_tag picture.image.url, class: "card-img-top"%> <% end %>
              </div>
              <div class="card-body">
                <h4 class="card-text"><%= picture.content %></h4>
                <div class="article-data card-text">
                  <span><%= picture.user.name %></span>
                  <h5><%= picture.created_at.strftime('%Y年%-m月%-d日 %H:%M') %></h5>
                </div>
                <div class="card-button">
                  <%= link_to picture_path(picture.id) do %>
                    <span class="bi bi-info-square" title="詳細"></span><% end %>
                  <% if picture.user.id == current_user.id %>
                    <%= link_to edit_picture_path(picture.id), data:{confirm:"こちらの投稿を編集しますか？"} do %>
                      <span class="bi bi-pencil-square" title="編集"></span><% end %>
                    <%= link_to picture_path(picture.id), method: :delete, data:{confirm:"こちらの投稿を削除しますか？"} do %>
                      <span class="bi bi-trash" title="削除"></span><% end %>
                  <% else %>
                    <span class="bi bi-pencil-square" title="編集不可"></span>
                    <span class="bi bi-trash" title="削除不可"></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="empty-wrapper">
          <%= image_tag '/assets/noimage.png', class: 'no-image' %>
          <h2>まだ記事がありません。</h2>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="post-wrapper">
  <div class="container-fluid">
    <div class="row justify-content-between">
      <%= render partial: "form", locals: { formtitle: "投稿の作成", btnlabel:"投稿する" } %>
    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="show-wrapper">
  <div class="container-fluid">
    <div class="article-container">
      <div>
        <div class="article-header">
          <div class="article-data">
            <strong><span><%= @picture.user.name %></span></strong>
            <h5><%= @picture.created_at.strftime('%Y年%-m月%-d日 %H:%M') %></h5>
          </div>
          <div class="article-edit-icon">
            <% if @picture.user.id == current_user.id %>
              <%= link_to edit_picture_path(@picture.id), data:{confirm:"こちらの投稿を編集しますか？"} do %>
                <span class="bi bi-pencil-square" title="編集"></span><% end %>
              <%= link_to picture_path(@picture.id), method: :delete, data:{confirm:"こちらの投稿を削除しますか？"} do %>
                <span class="bi bi-trash" title="削除"></span><% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div>
        <div class="article-content">
          <h4><%= @picture.content %></h4>
        </div>
        <div class="article-img-preview">
          <%= image_tag @picture.image.url %>
        </div>
      </div>
    </div>
  </div>

app/views/users/new.html.erb
<% content_for(:title, 'DPbook') %>
<div class="signup-wrapper">
  <div class="form-box">
    <div class="signup-form">
      <div class="signup-title">
        <h2>アカウント作成</h2>
        <span>以下の情報を入力してください。</span>
      </div>
      <div class="form-border"></div>
      <% if @user.errors.any? %>
        <div class="form-error-message">
          <h5>以下のエラーがあります。</h5>
          <div id="error_explanation">
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
      <div class="signup-input">
        <%= form_with(model: @user, local: true) do |f| %>
          <div class="input-group-lg input-container">
            <%= f.text_field :name, placeholder:"名前", class:"form-control form-control-lg", required: true %>
          </div>
          <div class="input-group-lg input-container">
            <%= f.email_field :email, placeholder:"メールアドレス", class:"form-control form-control-lg", required: true %>
          </div>
          <div class="input-group-lg input-container">
            <%= f.password_field :password, placeholder:"パスワード", class:"form-control form-control-lg", required: true %>
          </div>
          <div class="input-group-lg input-container">
            <%= f.password_field :password_confirmation, placeholder:"パスワード(再確認)", class:"form-control form-control-lg", required: true %>
          </div>
        </div>
        <div class="button-container">
          <%= f.submit "アカウント作成", class:"btn btn-success btn-lg w-50" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:title, '') %>
<div class="profile-wrapper">
  <h2>あなたのプロフィール</h2>
  <ul class="profile-list">
    <li>
      <h4>名前</h4>
      <span><%= @user.name %></span>
    </li>
    <li>
      <h4>メールアドレス</h4>
      <span><%= @user.email %></span>
    </li>
  </ul>
  <div>
  </div>
</div>